name: wedevs_testproject
description: Flutter project assigned by weDevs.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #implement hex colors to dart hexcolorPlugin
  hexcolor: ^2.0.5
  #include fonts from fonts.google.com in our Flutter app.
  google_fonts: ^2.2.0
  #for state management and implement BloC pattern
  flutter_bloc: ^7.3.1
  #implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.3
  #represent and validate flutter form in a generic way.
  formz: ^0.4.1
  #For adapting screen and font size. Display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.0.3
  #Toast Library for Flutter
  fluttertoast: ^8.0.8
  #Stunning Animating Curved Shape Navigation Bar.
  curved_navigation_bar: ^1.0.1
  #Future-based API for HTTP requests
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #community-driven set of lint rules for Dart and Flutter projects.
  lint: ^1.8.1


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/json/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
